name: Update README with Latest Versions

on:
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to get all tags

      - name: Extract latest tags
        id: tags
        run: |
          latest_breeze=$(git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          latest_edgeai=$(git tag --list 'EdgeAI-v*' | sort -V | tail -n 1)

          echo "BREEZE_VERSION=${latest_breeze}" >> $GITHUB_ENV
          echo "EDGEAI_VERSION=${latest_edgeai#EdgeAI-}" >> $GITHUB_ENV

      - name: Update README and EdgeAI Documentation
        run: |
          # Update main README placeholders
          sed -i "s/{{BREEZEAPP_ENGINE_VERSION}}/${BREEZE_VERSION}/" README.md
          sed -i "s/{{EDGEAI_VERSION}}/${EDGEAI_VERSION}/" README.md
          
          # Update EdgeAI documentation placeholders
          CURRENT_EDGEAI_VERSION="EdgeAI-${EDGEAI_VERSION}"
          
          # Update build.gradle.kts version (this stays hardcoded as it needs to be a real version)
          sed -i "s/version = \"EdgeAI-v[0-9]\+\.[0-9]\+\.[0-9]\+\"/version = \"${CURRENT_EDGEAI_VERSION}\"/" android/EdgeAI/build.gradle.kts
          
          # Update EdgeAI documentation placeholders  
          sed -i "s/{{EDGEAI_VERSION}}/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/README.md
          sed -i "s/{{EDGEAI_VERSION}}/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/docs/GETTING_STARTED.md
          sed -i "s/{{EDGEAI_VERSION}}/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/docs/i18n/GETTING_STARTED_zh.md
          
          # Update remaining hardcoded versions in SOP docs (these contain multiple examples)
          sed -i "s/EdgeAI-v[0-9]\+\.[0-9]\+\.[0-9]\+/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/docs/JitPack_Release_SOP.md
          sed -i "s/EdgeAI-v[0-9]\+\.[0-9]\+\.[0-9]\+/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/docs/i18n/JitPack_Release_SOP_zh.md
          
          # Update Chinese README if exists
          if [ -f "android/EdgeAI/docs/i18n/README_zh.md" ]; then
            sed -i "s/EdgeAI-v[0-9]\+\.[0-9]\+\.[0-9]\+/${CURRENT_EDGEAI_VERSION}/g" android/EdgeAI/docs/i18n/README_zh.md
          fi
          
          echo "Updated EdgeAI version to ${CURRENT_EDGEAI_VERSION} across all documentation"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b temp-update-readme   # create a branch from detached HEAD

          git add README.md android/EdgeAI/
          git commit -m "docs: update latest versions across all documentation [skip ci]" || echo "No changes to commit"
          git push origin temp-update-readme:main